// <auto-generated />
using System;
using Dystopian_Civil_Office.DataSource;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Dystopian_Civil_Office.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260523153424_InitialPipeline")]
    partial class InitialPipeline
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Dystopian_Civil_Office.Models.Archives.AddressArchive", b =>
                {
                    b.Property<int>("AddressArchiveId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("AddressArchiveId"));

                    b.Property<string>("ApartmentNumber")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DocumentName")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("HouseNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("PostalCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Street")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.HasKey("AddressArchiveId");

                    b.ToTable("address_archives", (string)null);
                });

            modelBuilder.Entity("Dystopian_Civil_Office.Models.Archives.BirthRecordArchive", b =>
                {
                    b.Property<int>("BirthRecordArchiveId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("BirthRecordArchiveId"));

                    b.Property<DateOnly>("BirthDate")
                        .HasColumnType("date");

                    b.Property<string>("BirthPlace")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("BornPersonPesel")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("character varying(11)");

                    b.Property<DateTime>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DocumentName")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("FatherPesel")
                        .HasMaxLength(11)
                        .HasColumnType("character varying(11)");

                    b.Property<string>("MotherPesel")
                        .HasMaxLength(11)
                        .HasColumnType("character varying(11)");

                    b.Property<DateOnly>("RegistryDate")
                        .HasColumnType("date");

                    b.Property<string>("RegistryNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("BirthRecordArchiveId");

                    b.ToTable("birth_record_archives", (string)null);
                });

            modelBuilder.Entity("Dystopian_Civil_Office.Models.Archives.DeathRecordArchive", b =>
                {
                    b.Property<int>("DeathRecordArchiveId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("DeathRecordArchiveId"));

                    b.Property<string>("CauseOfDeath")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateOnly>("DeathDate")
                        .HasColumnType("date");

                    b.Property<string>("DeathPlace")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DocumentName")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("PersonPesel")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("character varying(11)");

                    b.Property<DateOnly>("RegistryDate")
                        .HasColumnType("date");

                    b.Property<string>("RegistryNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("DeathRecordArchiveId");

                    b.ToTable("death_record_archives", (string)null);
                });

            modelBuilder.Entity("Dystopian_Civil_Office.Models.Archives.DocumentArchive", b =>
                {
                    b.Property<int>("DocumentArchiveId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("DocumentArchiveId"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("ImportDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.HasKey("DocumentArchiveId");

                    b.ToTable("document_archives", (string)null);
                });

            modelBuilder.Entity("Dystopian_Civil_Office.Models.Archives.MarriageRecordArchive", b =>
                {
                    b.Property<int>("MarriageRecordArchiveId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("MarriageRecordArchiveId"));

                    b.Property<DateTime>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DocumentName")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<DateOnly>("MarriageDate")
                        .HasColumnType("date");

                    b.Property<string>("MarriagePlace")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateOnly>("RegistryDate")
                        .HasColumnType("date");

                    b.Property<string>("RegistryNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Spouse1Pesel")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("character varying(11)");

                    b.Property<string>("Spouse2Pesel")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("character varying(11)");

                    b.HasKey("MarriageRecordArchiveId");

                    b.ToTable("marriage_record_archives", (string)null);
                });

            modelBuilder.Entity("Dystopian_Civil_Office.Models.Archives.PersonArchive", b =>
                {
                    b.Property<int>("PersonArchiveId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("PersonArchiveId"));

                    b.Property<DateOnly>("BirthDate")
                        .HasColumnType("date");

                    b.Property<string>("BirthPlace")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DocumentName")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("MiddleName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("PersonPesel")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("character varying(11)");

                    b.HasKey("PersonArchiveId");

                    b.ToTable("person_archives", (string)null);
                });

            modelBuilder.Entity("Dystopian_Civil_Office.Models.Entities.Address", b =>
                {
                    b.Property<int>("AddressId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("address_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("AddressId"));

                    b.Property<string>("ApartmentNumber")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("apartment_number");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("city");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("country");

                    b.Property<int?>("DocumentId")
                        .HasColumnType("integer")
                        .HasColumnName("document_id");

                    b.Property<string>("HouseNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("house_number");

                    b.Property<string>("PostalCode")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("character varying(15)")
                        .HasColumnName("postal_code");

                    b.Property<string>("Street")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("street");

                    b.HasKey("AddressId");

                    b.HasIndex("DocumentId")
                        .IsUnique();

                    b.ToTable("addresses", (string)null);
                });

            modelBuilder.Entity("Dystopian_Civil_Office.Models.Entities.BirthRecord", b =>
                {
                    b.Property<int>("BirthRecordId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("birth_record_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("BirthRecordId"));

                    b.Property<int?>("DocumentId")
                        .HasColumnType("integer")
                        .HasColumnName("document_id");

                    b.Property<int?>("FatherId")
                        .HasColumnType("integer")
                        .HasColumnName("father_id");

                    b.Property<int?>("MotherId")
                        .HasColumnType("integer")
                        .HasColumnName("mother_id");

                    b.Property<int>("PersonId")
                        .HasColumnType("integer")
                        .HasColumnName("person_id");

                    b.Property<DateOnly>("RegistryDate")
                        .HasColumnType("date")
                        .HasColumnName("registry_date");

                    b.Property<string>("RegistryNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("registry_number");

                    b.HasKey("BirthRecordId");

                    b.HasIndex("DocumentId")
                        .IsUnique();

                    b.HasIndex("FatherId");

                    b.HasIndex("MotherId");

                    b.HasIndex("PersonId")
                        .IsUnique();

                    b.HasIndex("RegistryNumber")
                        .IsUnique();

                    b.ToTable("birth_records", (string)null);
                });

            modelBuilder.Entity("Dystopian_Civil_Office.Models.Entities.DeathRecord", b =>
                {
                    b.Property<int>("DeathRecordId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("death_record_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("DeathRecordId"));

                    b.Property<string>("CauseOfDeath")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("cause_of_death");

                    b.Property<DateOnly>("DeathDate")
                        .HasColumnType("date")
                        .HasColumnName("death_date");

                    b.Property<string>("DeathPlace")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("death_place");

                    b.Property<int?>("DocumentId")
                        .HasColumnType("integer")
                        .HasColumnName("document_id");

                    b.Property<int>("PersonId")
                        .HasColumnType("integer")
                        .HasColumnName("person_id");

                    b.Property<DateOnly>("RegistryDate")
                        .HasColumnType("date")
                        .HasColumnName("registry_date");

                    b.Property<string>("RegistryNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("registry_number");

                    b.HasKey("DeathRecordId");

                    b.HasIndex("DocumentId")
                        .IsUnique();

                    b.HasIndex("PersonId")
                        .IsUnique();

                    b.HasIndex("RegistryNumber")
                        .IsUnique();

                    b.ToTable("death_records", (string)null);
                });

            modelBuilder.Entity("Dystopian_Civil_Office.Models.Entities.Document", b =>
                {
                    b.Property<int>("DocumentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("document_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("DocumentId"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("category");

                    b.Property<DateTime>("ImportDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("import_date");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.HasKey("DocumentId");

                    b.ToTable("documents", (string)null);
                });

            modelBuilder.Entity("Dystopian_Civil_Office.Models.Entities.MarriageRecord", b =>
                {
                    b.Property<int>("MarriageRecordId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("marriage_record_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("MarriageRecordId"));

                    b.Property<int?>("DocumentId")
                        .HasColumnType("integer")
                        .HasColumnName("document_id");

                    b.Property<DateOnly>("MarriageDate")
                        .HasColumnType("date")
                        .HasColumnName("marriage_date");

                    b.Property<string>("MarriagePlace")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("marriage_place");

                    b.Property<DateOnly>("RegistryDate")
                        .HasColumnType("date")
                        .HasColumnName("registry_date");

                    b.Property<string>("RegistryNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("registry_number");

                    b.Property<int>("Spouse1Id")
                        .HasColumnType("integer")
                        .HasColumnName("spouse1_id");

                    b.Property<int>("Spouse2Id")
                        .HasColumnType("integer")
                        .HasColumnName("spouse2_id");

                    b.HasKey("MarriageRecordId");

                    b.HasIndex("DocumentId")
                        .IsUnique();

                    b.HasIndex("RegistryNumber")
                        .IsUnique();

                    b.HasIndex("Spouse1Id");

                    b.HasIndex("Spouse2Id");

                    b.ToTable("marriage_records", null, t =>
                        {
                            t.HasCheckConstraint("ck_marriage_records_spouses_different", "\"spouse1_id\" <> \"spouse2_id\"");
                        });
                });

            modelBuilder.Entity("Dystopian_Civil_Office.Models.Entities.Person", b =>
                {
                    b.Property<int>("PersonId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("person_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("PersonId"));

                    b.Property<int>("AddressId")
                        .HasColumnType("integer")
                        .HasColumnName("address_id");

                    b.Property<DateOnly>("BirthDate")
                        .HasColumnType("date")
                        .HasColumnName("birth_date");

                    b.Property<string>("BirthPlace")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("birth_place");

                    b.Property<int?>("DocumentId")
                        .HasColumnType("integer")
                        .HasColumnName("document_id");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("first_name");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("gender");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("last_name");

                    b.Property<string>("MiddleName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("middle_name");

                    b.Property<string>("Pesel")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("character varying(11)")
                        .HasColumnName("pesel");

                    b.HasKey("PersonId");

                    b.HasIndex("AddressId");

                    b.HasIndex("DocumentId")
                        .IsUnique();

                    b.HasIndex("Pesel")
                        .IsUnique();

                    b.ToTable("persons", null, t =>
                        {
                            t.HasCheckConstraint("ck_persons_gender", "\"gender\" IN ('Male', 'Female', 'Other')");
                        });
                });

            modelBuilder.Entity("Dystopian_Civil_Office.Models.Entities.Address", b =>
                {
                    b.HasOne("Dystopian_Civil_Office.Models.Entities.Document", "Document")
                        .WithOne("Address")
                        .HasForeignKey("Dystopian_Civil_Office.Models.Entities.Address", "DocumentId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Document");
                });

            modelBuilder.Entity("Dystopian_Civil_Office.Models.Entities.BirthRecord", b =>
                {
                    b.HasOne("Dystopian_Civil_Office.Models.Entities.Document", "Document")
                        .WithOne("BirthRecord")
                        .HasForeignKey("Dystopian_Civil_Office.Models.Entities.BirthRecord", "DocumentId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Dystopian_Civil_Office.Models.Entities.Person", "Father")
                        .WithMany("BirthRecordsAsFather")
                        .HasForeignKey("FatherId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Dystopian_Civil_Office.Models.Entities.Person", "Mother")
                        .WithMany("BirthRecordsAsMother")
                        .HasForeignKey("MotherId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Dystopian_Civil_Office.Models.Entities.Person", "Person")
                        .WithOne("BirthRecord")
                        .HasForeignKey("Dystopian_Civil_Office.Models.Entities.BirthRecord", "PersonId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Document");

                    b.Navigation("Father");

                    b.Navigation("Mother");

                    b.Navigation("Person");
                });

            modelBuilder.Entity("Dystopian_Civil_Office.Models.Entities.DeathRecord", b =>
                {
                    b.HasOne("Dystopian_Civil_Office.Models.Entities.Document", "Document")
                        .WithOne("DeathRecord")
                        .HasForeignKey("Dystopian_Civil_Office.Models.Entities.DeathRecord", "DocumentId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Dystopian_Civil_Office.Models.Entities.Person", "Person")
                        .WithOne("DeathRecord")
                        .HasForeignKey("Dystopian_Civil_Office.Models.Entities.DeathRecord", "PersonId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Document");

                    b.Navigation("Person");
                });

            modelBuilder.Entity("Dystopian_Civil_Office.Models.Entities.MarriageRecord", b =>
                {
                    b.HasOne("Dystopian_Civil_Office.Models.Entities.Document", "Document")
                        .WithOne("MarriageRecord")
                        .HasForeignKey("Dystopian_Civil_Office.Models.Entities.MarriageRecord", "DocumentId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Dystopian_Civil_Office.Models.Entities.Person", "Spouse1")
                        .WithMany("MarriagesAsSpouse1")
                        .HasForeignKey("Spouse1Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Dystopian_Civil_Office.Models.Entities.Person", "Spouse2")
                        .WithMany("MarriagesAsSpouse2")
                        .HasForeignKey("Spouse2Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Document");

                    b.Navigation("Spouse1");

                    b.Navigation("Spouse2");
                });

            modelBuilder.Entity("Dystopian_Civil_Office.Models.Entities.Person", b =>
                {
                    b.HasOne("Dystopian_Civil_Office.Models.Entities.Address", "Address")
                        .WithMany("Persons")
                        .HasForeignKey("AddressId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Dystopian_Civil_Office.Models.Entities.Document", "Document")
                        .WithOne("Person")
                        .HasForeignKey("Dystopian_Civil_Office.Models.Entities.Person", "DocumentId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Address");

                    b.Navigation("Document");
                });

            modelBuilder.Entity("Dystopian_Civil_Office.Models.Entities.Address", b =>
                {
                    b.Navigation("Persons");
                });

            modelBuilder.Entity("Dystopian_Civil_Office.Models.Entities.Document", b =>
                {
                    b.Navigation("Address");

                    b.Navigation("BirthRecord");

                    b.Navigation("DeathRecord");

                    b.Navigation("MarriageRecord");

                    b.Navigation("Person");
                });

            modelBuilder.Entity("Dystopian_Civil_Office.Models.Entities.Person", b =>
                {
                    b.Navigation("BirthRecord");

                    b.Navigation("BirthRecordsAsFather");

                    b.Navigation("BirthRecordsAsMother");

                    b.Navigation("DeathRecord");

                    b.Navigation("MarriagesAsSpouse1");

                    b.Navigation("MarriagesAsSpouse2");
                });
#pragma warning restore 612, 618
        }
    }
}
